Repository a2lix/TranslationFormBundle, pull requests merged in 2018-03, with the labels that each got.

#292 Add license and Issue/PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
Labels: enhancement

#293 Symfony 4 support for 2.x branch
  .travis.yml
  composer.json
Labels: minor

#298 Fix wrong links
  README.md
Labels: pedantic

#300 Remove useless conditionals
  Tests/TranslationsTypeTestCase.php
Labels: pedantic

#301 Fix parent form type on SF3
  Form/Type/TranslatedEntityType.php
  Form/Type/TranslationsLocalesSelectorType.php
Labels: patch

#289 fix #246 + BC layer for SF < 2.7
  Form/Type/TranslatedEntityType.php
Labels: patch

#302 Manual merge
  CHANGELOG.md
  Form/Type/TranslatedEntityType.php
Labels: pedantic

#306 Fix Scope widening and missing request
  DependencyInjection/A2lixTranslationFormExtension.php
  Form/Type/TranslatedEntityType.php
  UPGRADE-2.x.md
Labels: patch

#308 Remove call to setRequest
  Resources/config/services.xml
Labels: patch
